name: C++ CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cmake .
      - run: cmake --build .
      - run: ./example
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
      - run: clang-tidy -p . include/split_string.hpp
